name: Test

on:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            ZOTONIC_DIR: /tmp/zotonic

        services:
            postgres:
                image: postgres:9.5.5-alpine
                env:
                    POSTGRES_USER: zotonic
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.0

            -   name: Set up Erlang
                uses: erlef/setup-beam@v1.10.0
                with:
                    otp-version: "21.3"

            -   name: Install and configure Zotonic
                run: |
                    git clone https://github.com/zotonic/zotonic.git $ZOTONIC_DIR --branch 0.x
                    mkdir -p ~/.zotonic/0 ${ZOTONIC_DIR}/user
                    sed "s|\.\.\/ginger/modules|$GITHUB_WORKSPACE/modules|" config/zotonic.config > ~/.zotonic/0/zotonic.config

            -   name: Install dependencies
                run: |
                    git clone https://github.com/driebit/mod_elasticsearch.git modules/mod_elasticsearch

            -   name: Compile
                working-directory: ${{ env.ZOTONIC_DIR }}
                run: make all

            -   name: Run tests
                working-directory: ${{ env.ZOTONIC_DIR }}
                env:
                    ERL: "erl -noshell"
                run: $GITHUB_WORKSPACE/scripts/runtests.sh
